# Generated by Django 3.1.1 on 2021-04-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comite',
            name='nombre_comite',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
